sudo: false
language: haskell
cabal:
  - "2.2"
  - "2.4"
ghc:
  - "8.0"
  - "8.2"
  - "8.4"
  - "8.6"
before_install:
  - cabal v2-install alex
  - cabal v2-install happy
  - cabal v2-install c2hs
  - sudo apt install mesa-opencl-icd opencl-headers
