sudo: false
language: haskell
ghc:
  - 8.0
  - 8.2
  - 8.4
  - 8.6
before_install:
  - cabal v2-install alex
  - cabal v2-install happy
  - cabal v2-install c2hs
  - sudo apt install opencl-icd opencl-headers
